language: python

python:
  - "3.8.2"

addons:
  postgresql: "9.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
- coverage run --source='.' manage.py test
- coverage report 

after_success:
  - coveralls